### ISSUE TITLE
Problem again

### ISSUE THREAD

**Issue by kaushin** [fgwei/amandroid-build#2]
Im sorry,but I ran into another problem again, I am extremely sorry to bother you again.
The problem is when i try to run amandroid in linux .
for example - amandroid org.sireum.amandroid.csm.HideAPI_run 
it gives me a command not found
then if i run - ./amandroid org.sireum.amandroid.csm.HideAPI_run
it give me a failed to download Java error, to which i have manually downloaded from ZULU and placed in the platform folder , but when I run the above command again it gives me the same error and also removes all the files in the platform folder. I am attaching a screen shot of the error I received.
I apologize for the inconvenience caused by me.
Thank you,
Kaushik Nimmala.
![error2](https://cloud.githubusercontent.com/assets/14333928/13962675/71157864-f038-11e5-9e26-c1b8d781938f.png)

**Comment by kaushin** [comment]
I removed the --show-progress option from the amandroid file. that seemed to work , but im getting a class not found exception now :(

**Comment by fgwei** [comment]
I updated amandroid-build, you can try the new one again. For the --show-progress problem, you should have wget version higher than 1.6

**Comment by fgwei** [comment]
I removed the --show-progress option to make it work for more version of wget.
